[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 5173
  framework = "vite"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "prisma"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/socket.io/*"
  to = "/.netlify/functions/socket"
  status = 200
  force = true

[functions."socket"]
  included_files = ["server/**", "prisma/**"]
  node_bundler = "esbuild"

[functions."api"]
  included_files = ["server/**", "prisma/**"]
  node_bundler = "esbuild"

